### ISSUE TITLE
Outlook mac autolinking

### ISSUE THREAD

**Issue by M-J-Robbins** [JayOram/email-css-resets#10]
Outlook on mac is adding 
`<span id="WEBEXT" contextualstring="Suite‌ 43920‌, ‌Beaverton‌, ‌Oregon‌ 97008" style="color: rgb(0, 114, 198); text-decoration: none; border-bottom-width: 1px; border-bottom-style: dashed; border-bottom-color: currentcolor;">`

This isn't rendered as a link as such so we cant target it with an `a{}` but they do add an id, so we can remove all the styles by using 
```css
#WEBEXT{
  all:revert !important;
}
```

**Comment by JayOram** [comment]
Added to [CSS links reset md file](https://github.com/JayOram/email-css-resets/blob/main/css-link-resets.md): 

*Outlook on mac*

Submitted by [Mark Robbins](https://github.com/M-J-Robbins) - more information in [issue #10](https://github.com/JayOram/email-css-resets/issues/10).

```
#WEBEXT{
  all:revert !important;
}
```
