### ISSUE TITLE
Gmail iOS .body reset

### ISSUE THREAD

**Issue by M-J-Robbins** [JayOram/email-css-resets#2]
On iOS Gmail sets this code
```
body {
  -webkit-text-size-adjust: none;
  background-color: #ffffff;
  color: #313131;
  font-family: Roboto;
  font-size: 16px;
  line-height: 1.4;
  margin: 0;
  margin-right: 15px;
  padding: 0;
  word-spacing: 1px;
  word-wrap: break-word;
  min-height: 10px;
}
``` 
As discussed here https://github.com/hteumeuleu/email-bugs/issues/80#issuecomment-635257421

The `word-wrap` and `word-spacing` are not standard and can cause issues.  We can fix it with 
```
.body{
   word-wrap: normal;
   word-spacing:normal;
}
```
This also requires adding a class of body to the body `<body class="body">` 

However this doesn't fix the issue for GANGA so it's probably better done inline.
`<body style="word-wrap: normal; word-spacing:normal;">`

**Comment by JayOram** [comment]
Added to CSS-normalise - thanks Mark!
